export const GENERATE_IMAGE_REQUEST = "GENERATE_IMAGE_REQUEST";
export const GENERATE_IMAGE_FAILUER = "GENERATE_IMAGE_FAILUER";
export const GENERATE_IMAGE_SUCCESS = "GENERATE_IMAGE_SUCCESS";

export const POST_IMAGE_REQUEST = "POST_IMAGE_REQUEST";
export const POST_IMAGE_FAILUER = "POST_IMAGE_FAILUER";
export const POST_IMAGE_SUCCESS = "POST_IMAGE_SUCCESS";

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST";
export const DELETE_IMAGE_FAILUER = "DELETE_IMAGE_FAILUER";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
